language: ruby
rvm:
- 2.3.3
branches:
  only:
  - master
before_install:
- chmod u+x deploy_init.sh
- bash deploy_init.sh
- npm install
before_script:
- gulp jsmin_travis
script:
- bundle exec jekyll build
- gulp imagemin
before_deploy:
- chmod u+x deploy.sh
deploy:
  provider: script
  script: "./deploy.sh"
  skip_cleanup: true
sudo: false
env:
  global:
    secure: ryY/cl28DMX9iobuqgKre2h1TwtjD6F5WpBBd2NeDeIxfIswoMJr0L+2OPZozDgbjgzrMEQYyqWOZSWk9WB4mjdRl10MXv6FoD8tGMK5i48da86kMtw57ahp7O3oNvrhl/PtNC2K4Z04zvLfi7py+SBg4vo1bOyV2jNjs96kTa2DOf8kBHyZXMeswpIDikQDH7GZHHkEZ6W8+sqesC/tPqtwtZG883guScKvJeIaE0uGfnxtvl2+D+AsBwGxB9DJs6bY5tyTjh7iDUD7I1h3cwWlInpmpSue9cvS0P6KJEVxUUqGxyVdbng3LDialyYWtduOUw1UyJwvBW15jomsNj+XwuNhumt6vvzLF6fiQLvSUzxZNtpe/hQB8iLVtIA2Gvgprh9M0ovc0IiNAb7SfLqGQAvUo//7LH0LdfNhudQ0EOuhVjSEM/i5nfoJdkHLhFR/VP2+Hmmd6ZfrbFaFcLE901hIPqKPhhBM1yj+ynhLuqkqlJSTo7ZUfJWRwjxfTY9AJoy9qtppv0QbcrbkwascOxlLUaDBky9kji6Z/hyNe7x+A5QDVdDHlxQyk2lNYmKf/jDv5Xg1lObQmoeXWpx2JsnogVPjClk0r17ulYxL62/DyhrbbryFVwn9wErySR1xP4q03XT/8dm4FzgpCqAidJ/LQt9J6f85HDPQ3jE=
